### ISSUE TITLE
split preset in one preset per country

### ISSUE THREAD

**Issue by Klumbumbus** [yopaseopor/traffic_signs_preset_JOSM#11]
I think it would be useful to split this preset in one preset per country. This would reduce the download size (this preset is more than twice as big as the whole JOSM program). Traffic signs usually need on the ground survey before you tag them. So mappers usually map traffic signs only in one country anyway. Another problem is that currently the tags/membership dialog is filled with unnecessary preset links, which makes this preset unusable for me.

![traffic_sign_preset_links](https://cloud.githubusercontent.com/assets/7115609/17700188/ffc3c520-63c4-11e6-83c4-08d6ab07a717.png)

**Comment by yopaseopor** [comment]
I thought about it some months ago, when I start to do more than only "Spanish" traffic signs (with all the pass limit of the JOSM wiki "affaire").
I know this preset it is so big...because traffic signs in will be a big thing. Mapillary and OSV thinks this also - and all the automatic driving car stuff too). In [Taginfo] (http://taginfo.openstreetmap.org/projects/traffic_signs#tags) you can see we are taking about 10000+ values (covering all possibilities forward,backward, and no direction).
More of these values...don't have any node on OSM...yet, countries like Austria or Poland has no traffic signs... They don't care about it... yet (you can be sure next years they will , as all big countries in the world).

Because big projects starts one day from 0 or something like that. Talking about Mapillary. Who insane drunken bear thought one day you can "capture" your track whenever wherever you are and upload it!!??...Well, two or three years later 77,844,079 photos and 1,808,785,011 meters later tell us it is a possible project. 

Imagine you are a biologist...And you care about...trees, and you discover OSM. And the best tool to work with it is JOSM. What about introducing ALL trees species, What about a preset with 200 species?

You watch [there]( http://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree) more than 200+ species. Then you can manage them by country, by type of leaf...so you start to have some repeated tags in some countries. But what about...PLANTS? (more than 300000+ species)
Big things... have big sizes. I know it is a heavy thing (I had to "recopile" more than 3000 icons from 17 country wiki pages) . And I'm building it. Now the preset works only with Spain, Belgium , The Nederlands and Finland (last in construction) but it is all structured and prepared for other countries (you know I am very bad programming so having all structured and planned is a big part of my "work" for me). Style works on Austria, Belgium, Czech Republic, Belarus, Germany, Denmark,Estonia,Finland,France,The Nederlands, Norway, Poland and Sweden.

You have reason, working with plenty of it is so complicated ,for this reason you can "split the preset itself" adding the chosen country in the toolbar (it would be interesting the possibility of show only the parts I want of a preset in JOSM menús - not only toolbar...or make toolbar bigger...) . I made this in that way because I don't want to "flood" JOSM with 10 or 20 different but similar presets. In this way I try to do a complete tool, you download it and then you choose what you need  and put it on toolbar. I don't know any big thing about programming, Spanish and Catalan community helps me when I break something in JOSM (I'm so sorry about that) and try to fix it (like travis-ci, etc.). Always I try my best.

I think preset links in tags window are annoying too. But I think is not only a preset's fault. Some traffic signs items contains also some common tags used in OSM as hotels, restaurants, camp sites, stop,give way, traffic_lights ..., also as a start of unite same traffic signs of different countries with common keys. If you choose a traffic sign with only two-letter country code you don't have any problem with preset links in tags window. But... if you have 10 presets taking about one same thing, and if you select this one thing then you will have the same problem with preset links. I think the possibility of disabling JOSM preset links in tag windows (in expert mode? in parameters?) would be interesting.

Thank you for your attention

**Comment by Klumbumbus** [comment]
Lots of text but I don't really understand what you actually want to say.

I think the preset is about traffic signs so it should tag the two letter country codes in the traffic_sign key and not things like amenity=restaurant or aeroway=aerodrome. The traffic sign is not the POI. Removing the POI tags from the preset would fix the list of linked presets in the tags/membership dialog.

The other way round if I tag a node with traffic_sign=ES:P12 or traffic_sign:forward=ES:P12 your preset is not linked at all. Have a look at the key "match" at https://josm.openstreetmap.de/wiki/TaggingPresets to adjust the linking in the tags/membership dialog.

**Comment by yopaseopor** [comment]
Hey! You are right about splitting the preset so it's done. Now you have 29 traffic_signs basic presets. I wish now will be useful for you. Thank you for your great idea :)

**Comment by Klumbumbus** [comment]
OK, I see one missing icon in the german preset: traffic_signs/ES/ES_r2.png
